class Action(object):

    # __slots__ = [ 'do' ]

    def __init__(self, do=None):
        """
        The Action is just a wrapper around a simple string action type.
        They are generated by plan() methods on a provider, and processed by the apply() methods, 
        where they are sent in as a list.  The should() method on a provider actually processes
        the entire list of actions, not just this one object.
        """
        self.do = do

    def should(self, match):
        return self.do == match

    def __str__(self):
        return str(self.do)
